"""
flower_names.py

Oxford Flowers 102 Dataset
Official class names

Usage:
    from utils.flower_names import FLOWER_NAMES

    print(FLOWER_NAMES[label])
"""

FLOWER_NAMES = [
    "Pink Primrose",
    "Hard-leaved Pocket Orchid",
    "Canterbury Bells",
    "Sweet Pea",
    "English Marigold",
    "Tiger Lily",
    "Moon Orchid",
    "Bird of Paradise",
    "Monkshood",
    "Globe Thistle",
    "Snapdragon",
    "Colt's Foot",
    "King Protea",
    "Spear Thistle",
    "Yellow Iris",
    "Globe Flower",
    "Purple Coneflower",
    "Peruvian Lily",
    "Balloon Flower",
    "Giant White Arum Lily",
    "Fire Lily",
    "Pincushion Flower",
    "Fritillary",
    "Red Ginger",
    "Grape Hyacinth",
    "Corn Poppy",
    "Prince of Wales Feathers",
    "Stemless Gentian",
    "Artichoke",
    "Sweet William",
    "Carnation",
    "Garden Phlox",
    "Love in the Mist",
    "Mexican Aster",
    "Alpine Sea Holly",
    "Ruby-lipped Cattleya",
    "Cape Flower",
    "Great Masterwort",
    "Siam Tulip",
    "Lenten Rose",
    "Barbeton Daisy",
    "Daffodil",
    "Sword Lily",
    "Poinsettia",
    "Bolero Deep Blue",
    "Wallflower",
    "Marigold",
    "Buttercup",
    "Oxeye Daisy",
    "Common Dandelion",
    "Petunia",
    "Wild Pansy",
    "Primula",
    "Sunflower",
    "Pelargonium",
    "Bishop of Llandaff",
    "Gaura",
    "Geranium",
    "Orange Dahlia",
    "Pink-Yellow Dahlia",
    "Cautleya Spicata",
    "Japanese Anemone",
    "Black-eyed Susan",
    "Silverbush",
    "Californian Poppy",
    "Osteospermum",
    "Spring Crocus",
    "Bearded Iris",
    "Windflower",
    "Tree Poppy",
    "Gazania",
    "Azalea",
    "Water Lily",
    "Rose",
    "Thorn Apple",
    "Morning Glory",
    "Passion Flower",
    "Lotus",
    "Toad Lily",
    "Anthurium",
    "Frangipani",
    "Clematis",
    "Hibiscus",
    "Columbine",
    "Desert Rose",
    "Tree Mallow",
    "Magnolia",
    "Cyclamen",
    "Watercress",
    "Canna Lily",
    "Hippeastrum",
    "Bee Balm",
    "Pink Quill",
    "Foxglove",
    "Bougainvillea",
    "Camellia",
    "Mallow",
    "Mexican Petunia",
    "Bromelia",
    "Blanket Flower",
    "Trumpet Creeper",
    "Blackberry Lily"
]

# Category Number -> Flower Name
ID_TO_NAME = {i: name for i, name in enumerate(FLOWER_NAMES)}

# Flower Name -> Category Number (for use in the search function)
NAME_TO_ID = {name.lower(): i for i, name in enumerate(FLOWER_NAMES)}